### ISSUE TITLE
Aggiungere la sezione "Navigazione" ad ogni pagina

### ISSUE THREAD

**Issue by patchouli2** [Umbrawiki/wiki-issue#10]
Questa sezione va alla fine di ogni pagina. Qui ci vanno le navbox (non ancora create, eccetto quella degli angeli). Ad esempio, prendiamo Bayonetta (personaggio). Alla fine della sua pagina, la sezione dovrebbe essere così:
==Navigazione==
{{Personaggi}}
{{Bayonetta}}
{{Bayonetta2}}

La navbox "Personaggi" perché Bayonetta fa parte dei personaggi, se fosse stata un'arma, ci sarebbe andata la navbox delle Armi, e così via. Le navbox dei giochi poiché Bayonetta compare in quei giochi.

**Comment by Cruifer** [comment]
- primo test: `python pwb.py add_text -page:"Amante di Sergey" -summary:"Bot: adding navboxes" -text:"==Navigazione==\n{{Armi}}\n{{Bayonetta}}"`
- 2: `python pwb.py replace -start:! -summary:"Bot: adding Navigazione section" -excepttext:"==Navigazione==" -regex -always "{{[Aa]ngeli}}" "==Navigazione==\n{{Angeli}}" " == Voci correlate ==" "==Navigazione=="`
- 3: `python pwb.py add_text -cat:"Armi" -summary:"Bot: adding navboxes" -except:"{{[Aa]rmi}}" -text:"==Navigazione==\n{{Armi}}"`
