### ISSUE TITLE
Togliere qualsiasi collegamento a Discord

### ISSUE THREAD

**Issue by patchouli2** [Umbrawiki/wiki-issue#2]
Bisogna togliere il collegamento di Discord nella sidebar e nel tabellone dei social nella pagina principale, dal momento che il server è stato trasformato in una zona dedicata esclusivamente al wiki e quindi non aperta al pubblico (telegram sarà la principale forma di comunicazione).

**Comment by Cruifer** [comment]
fatto, chiudo la issue
